# CoastCams Configuration File
#
# This file contains all configuration parameters for CoastCams analysis.
# Edit these values to customize your analysis.
#
# For non-experts: The default values should work well for most cases.
# Only modify if you have specific requirements.

# ============================================================================
# Camera Parameters
# ============================================================================
camera_height: 27.24  # Camera height above mean sea level (meters)
pixel_resolution: 0.1  # Pixel resolution (meters/pixel)
rotation_angle: 270  # Image rotation angle (degrees: 0, 90, 180, 270)
acquisition_frequency: 2.0  # Image acquisition rate (Hz, images per second)

# ============================================================================
# Image Processing Parameters
# ============================================================================
cross_shore_width: 1600  # Number of pixels for cross-shore analysis
min_cross_shore: 1  # Minimum pixel for analysis (usually 1)
max_cross_shore: null  # Maximum pixel (null = auto-detect)

# ============================================================================
# Shoreline Detection
# ============================================================================
# Method selection:
#   1 = Grayscale intensity (best for rocky platforms)
#   2 = Red-minus-Blue (best for sandy beaches)
#   3 = Color convergence (best for mixed environments)
shoreline_method: 1
shoreline_threshold: 30  # Intensity threshold for detection (0-255)

# ============================================================================
# Wave Analysis Parameters
# ============================================================================
time_lag: 1  # Time lag for phase correlation (frames)
correlation_spacing: 100  # Spacing between correlation windows (pixels)
wave_period_min: 4.0  # Minimum expected wave period (seconds)
wave_period_max: 25.0  # Maximum expected wave period (seconds)

# ============================================================================
# Physical Constants
# ============================================================================
gravity: 9.81  # Gravitational acceleration (m/s²)
water_density: 1025  # Seawater density (kg/m³)

# ============================================================================
# Filtering Parameters
# ============================================================================
lowpass_cutoff: 0.05  # Low-pass filter cutoff frequency (Hz)
highpass_cutoff: 0.005  # High-pass filter cutoff frequency (Hz)
filter_order: 5  # Butterworth filter order
smoothing_window: 3  # 2D smoothing window size (pixels)

# ============================================================================
# Output Parameters
# ============================================================================
output_interval: 15  # Resampling interval for output (minutes)
save_plots: true  # Save visualization plots
save_intermediate: false  # Save intermediate processing results
output_format: csv  # Output file format: 'csv', 'excel', or 'both'

# ============================================================================
# File Paths
# ============================================================================
# These paths are auto-detected if not specified
# Relative paths are relative to the script location
input_dir: ../Timestacks  # Input directory for timestack images
output_dir: ../Output  # Output directory for results
coordinate_file: null  # Optional coordinate transformation file

# ============================================================================
# Visualization Options
# ============================================================================
plot_shoreline: true  # Plot shoreline detection results
plot_waves: true  # Plot wave parameter time series
plot_bathymetry: true  # Plot bathymetry profiles
plot_timeseries: true  # Plot comprehensive time series

# ============================================================================
# Advanced Options
# ============================================================================
use_coordinate_transform: false  # Apply coordinate transformation
parallel_processing: false  # Use multiprocessing (experimental)
verbose: true  # Print progress messages

# ============================================================================
# Notes for Users
# ============================================================================
#
# Getting Started:
# 1. Place your timestack images in the 'Timestacks' directory
# 2. Run: python main.py
# 3. Results will be saved to the 'Output' directory
#
# Customization:
# - Adjust 'shoreline_method' if detection isn't working well
# - Modify 'wave_period_min' and 'wave_period_max' for your site
# - Change 'camera_height' and 'pixel_resolution' to match your setup
#
# For more information, see README_PYTHON.md
